const ALERT = "ALERT"
const REFRESH_CHATS = "REFRESH_CHATS"
const NEW_ATTACHMENTS = "NEW_ATTACHMENTS"
const NEW_MESSAGEALERTS = "NEW_MESSAGEALERTS"
const NEW_MESSAGES = "NEW_MESSAGES"


module.exports = { ALERT, REFRESH_CHATS, NEW_ATTACHMENTS, NEW_MESSAGEALERTS }